### signup
POST https://projeto-cookenu.onrender.com/user/signup
Content-Type: application/json

{
    "name": "Julia Marques 2",
    "email": "julia2@gmail.com",
    "password": "123456"
}

### login
POST https://projeto-cookenu.onrender.com/user/login 
Content-Type: application/json

{
    "email": "julia2@gmail.com",
    "password": "123456"
}

### get Data user
GET https://projeto-cookenu.onrender.com/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmMDMyOTFkLTk3ZDItNGQ2Ny1iMTM5LTU1YTFlNTE2ZTY1OCIsImlhdCI6MTY3NjgzNDIxMywiZXhwIjoxNjc2ODM3ODEzfQ.2ZENUIzc7ImmS4o6u55HF1Y8zTXwPQM05LQLKk7G7Lo

### create Recipe
POST https://projeto-cookenu.onrender.com/user/createRecipe
Content-Type: application/json

{
   "title": "Macarronada", 
   "description": "Macarrão, Oléo, Molho, Sal. Modo de Preparo: Ferve água, adicione o macarrão, prepare o molho, coloque o sal, misture o molho no macarrão e sirva-se!", 
   "created_at": "12/02/2023",
   "user_id": "9c6191e2-96f1-4766-b6da-b6bec49ef481"
}

### add friend 
POST https://projeto-cookenu.onrender.com/user/friend
Content-Type: application/json

{
    "user_id": "2afbe1e8-c33c-4122-884b-4a9f0c11135b", 
    "follower_id": "69a3ca5f-55a9-48cd-aeb2-d8764c5161f2"
}

### feed 
GET https://projeto-cookenu.onrender.com/user/feed/69a3ca5f-55a9-48cd-aeb2-d8764c5161f2
