### signup
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Julia Marques 3",
    "email": "julia3@gmail.com",
    "password": "123456"
}

### login
POST http://localhost:3003/user/login 
Content-Type: application/json

{
    "email": "julia3@gmail.com",
    "password": "123456"
}

### get Data user
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmODFkODhkLWU5ZjMtNDIxYi04OTY2LTZkNDE1ZjJlMGZiZSIsImlhdCI6MTY3NzMyNTQzNSwiZXhwIjoxNjc3NDExODM1fQ.MJUvTpwaZwBlnPBTT-4Wl1zUxtJAswX5Yyv3e4AKPwA

### get Data user by id
GET http://localhost:3003/user/2f81d88d-e9f3-421b-8966-6d415f2e0fbe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmODFkODhkLWU5ZjMtNDIxYi04OTY2LTZkNDE1ZjJlMGZiZSIsImlhdCI6MTY3NzMyNTQzNSwiZXhwIjoxNjc3NDExODM1fQ.MJUvTpwaZwBlnPBTT-4Wl1zUxtJAswX5Yyv3e4AKPwA

### create Recipe
POST http://localhost:3003/user/createRecipe
Content-Type: application/json

{
   "title": "Macarronada", 
   "description": "Macarrão, Oléo, Molho, Sal. Modo de Preparo: Ferve água, adicione o macarrão, prepare o molho, coloque o sal, misture o molho no macarrão e sirva-se!", 
   "user_id": "2f81d88d-e9f3-421b-8966-6d415f2e0fbe"
}

### edit recipe
PUT http://localhost:3003/user/edit/2f81d88d-e9f3-421b-8966-6d415f2e0fbe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmODFkODhkLWU5ZjMtNDIxYi04OTY2LTZkNDE1ZjJlMGZiZSIsImlhdCI6MTY3NzMyNTA4NywiZXhwIjoxNjc3NDExNDg3fQ.lk-4cxAcar_YsAGreSdSZST3galwPRhXna3QCPvXwoI

{
   "title": "Macarronada com azeitona", 
   "description": "Macarrão, muita azeitona, Oléo, Molho, Sal. Modo de Preparo: Ferve água, adicione o macarrão, prepare o molho, coloque o sal, misture o molho no macarrão e sirva-se!", 
   "created_at": "23/02/2023",
   "user_id": "52cccfeb-eeae-4901-96c0-99aeedf4f839"
}

### get recipe by id
GET http://localhost:3003/recipe/52cccfeb-eeae-4901-96c0-99aeedf4f839
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmODFkODhkLWU5ZjMtNDIxYi04OTY2LTZkNDE1ZjJlMGZiZSIsImlhdCI6MTY3NzMyNTA4NywiZXhwIjoxNjc3NDExNDg3fQ.lk-4cxAcar_YsAGreSdSZST3galwPRhXna3QCPvXwoI

### add friend 
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YTNjYTVmLTU1YTktNDhjZC1hZWIyLWQ4NzY0YzUxNjFmMiIsImlhdCI6MTY3NzAxODc4MywiZXhwIjoxNjc3MTA1MTgzfQ.Rjyu7slQKBTRatrjYDgV3JjU0HqyJ241F8YRVnG1L0M

{
    "userToFollowId": "ad2b733a-29da-49c6-b41a-42322bdcd184"
}

### get feed 
GET http://localhost:3003/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmODFkODhkLWU5ZjMtNDIxYi04OTY2LTZkNDE1ZjJlMGZiZSIsImlhdCI6MTY3NzMyNTA4NywiZXhwIjoxNjc3NDExNDg3fQ.lk-4cxAcar_YsAGreSdSZST3galwPRhXna3QCPvXwoI


